### ISSUE TITLE
Cache preregistration page for ~15s (/uber/preregistration/form)

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem-puppet#135]
Per our [load tests](https://docs.magfest.net/display/EN/Uber+Preregistration+Load+Test+Results+2017-05-16), in order to handle the preregistration traffic spike, we should cache our preregistration form.

The preregistration form can't be cached in perpetuity because it will change as more people register (badge prices will increase). But even caching it for a short window - like 15 seconds - will make a huge difference when we get a wave of people registering.

**Comment by bds002** [comment]
What happens if someone gets served a page with an incorrect price if they
visit during that 15 second overlap? It  may happen on opening day.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by binary1230** [comment]
re-posting, email came out wrong.

Nick asked: "What happens if someone gets served a page with an incorrect price if they
visit during that 15 second overlap? It  may happen on opening day."

**Comment by RobRuana** [comment]
Great question! We have no mechanism in place to handle that, and maybe fixing that should be a part of this issue.

I believe this is actually an issue with the current system – if the price gets bumped in between the time that the preregistration page loads, and the time the user finishes filling out their info.

**Comment by kitsuta** [comment]
That's a good question. At first I was figuring that it would simply charge them the old price, but we're not caching the badge price itself.

What is likely best, if we can get away with it, is to NOT cache the index page and especially not stripeForm.html. Those are the pages that actually show what the attendee will pay. Then, worst case, the prereg form will say one price but the cart will say another -- which could in any case happen anyway if someone happened to finish filling out their badge at just the right (wrong?) time.

If we're concerned about people getting mad about this (and that's a fair concern!) I might advise being up-front when we launch prereg and saying something like, "In order to handle everyone descending on us at once, the main form only updates every 15 seconds! Please double-check the price in your cart before paying!"

**Comment by kitsuta** [comment]
In the Far Future we'll want to have a real cart system that reserves prices when you start filling out for badges, but I think that is out of scope for this year. Maybe not?

**Comment by RobRuana** [comment]
+1 for the real cart system.

**Comment by binary1230** [comment]
one solution, the cached data lives in /var/nginx/something, we could write a script for magbot that blows that dir away on price point changes.

or, even do it as a daemon inside uber that just checks on price levels and blows the dir away whenever a change is detected.  kinda breaks the abstraction a little but THIS IS WAR YO.  WE WILL WIN THIS BATTLE

or, yea, if it's 15 seconds and the price difference is $5...... eh.   if someone emails and complains about it we can refund just that one person.

also, maybe we'll structure the pricing based on the data from last year so the first day's regs don't actually increase in price. or something.

---

one other thing, /preregistration/form is linked in a bunch of different pages, maybe potentially the badge transfer page and the transfer badge page (I think? actually not sure i may be making that up).  we would just need to ensure that whatever links to this form in various scenarios is covered ok

**Comment by binary1230** [comment]
one other test btw:   we should probably measure the rendering time for a blank or simple page vs the prereg form page.  see if that makes any difference.  curious if there's like a slow part of the page rendering itself where it hits the DB, or if it's actually the rendering.   also, if any kind of slowness due to loading the files off the fs, maybe could cache the source templates in memory or something like that.

**Comment by RobRuana** [comment]
We can definitely test serving up a static html page from our python process. Although, I'm like 90% sure the template rendering is what is taking up most of our response time. From the profiler, the operations that consume the most time are:
```
44/18    0.000    0.000   19.244    1.069 {method 'join' of 'str' objects}
    1    0.000    0.000   19.244   19.244 /usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py:993(render)
```

Which looks to me like concatenating strings inside the jinja render function.

**Comment by kitsuta** [comment]
The template included on other pages is regform.html, not preregistration/form. Without knowing better how caching works, I can't say for sure that it won't get weird but it should be fine.

Although, come to think about it... stupid question, but, how is the page going to render correctly for editing preregs? If it's cached as a static page, the form will always be blank. Same question for when people get validation errors -- won't the form just blank out completely for every time someone gets an error? That sounds... unworkable.

**Comment by RobRuana** [comment]
I've been thinking about how we could handle editing preregs. Nginx allows a lot of customization for what is cached and under what conditions. Perhaps the easiest thing we can do is set up two different URLs that both go to "/uber/preregistration/form", one is cached by nginx and one isn't.

Maybe visiting "/uber/preregistration" serves up the cached page, whereas "/uber/preregistration/form" is always generated dynamically. Then we make all of our public links point directly to "/uber/preregistration".

Alternatively, we can instruct nginx to use the cache ONLY if there are no query parameters. Since editing an existing prereg uses an `edit_id` parameter like so:
```
/uber/preregistration/form?edit_id=bcad5e4a-66e5-4daf-91af-e21b7e7b3908
```

I think that may be the correct solution. Regardless, there are a lot of ways to fine tune our cache.

**Comment by RobRuana** [comment]
Now that I think about it, I'm pretty sure nginx doesn't cache requests with query params by default, so we're probably already good on that front!

**Comment by kitsuta** [comment]
Oh, phew! I was really worried there for a minute. Good to know that caching isn't just an on or off thing.

**Comment by binary1230** [comment]
All good first stabs at approaches.  Some stuff to pay attention to:  our current caching config doesn't cache the set-cookie header (because it would cache the session Id of the first page request and serve that up to unrelated users) so we'd have to work on a way around that, which could be tough/annoying.  

nginx.pp, in this repo, contains the caching info that gets written to nginx.  When playing with caching params, I found it easiest to ignore puppet, edit the live nginx config files on a staging server (or, locally), and then when I had the changes working, port them into puppet versions

I still wonder rather than deal with all the cookie complexity and query string stuff, if it might be easier to do this as an in memory cache of the template render output in python itself, or perhaps just trying to optimize or simplify the prereg form output, which is a crazy complex form full of db queries and other stuff.

**Comment by RobRuana** [comment]
> nginx.pp, in this repo, contains the caching info that gets written to nginx. When playing with caching params, I found it easiest to ignore puppet, edit the live nginx config files on a staging server (or, locally), and then when I had the changes working, port them into puppet versions

Hah! I do the exact same thing!

> I still wonder rather than deal with all the cookie complexity and query string stuff, if it might be easier to do this as an in memory cache of the template render output in python itself, or perhaps just trying to optimize or simplify the prereg form output, which is a crazy complex form full of db queries and other stuff.

I had the same thought, but I think the "correct" way to do this is via nginx caching (or varnish, but working varnish into our deployment structure would be a big lift). We're not the first people to encounter these issues, and nginx definitely has facilities to do what we need to do.

Python is in my wheelhouse, so whenever I encounter something I'm not entirely familiar with my default response is, "I'll just do this in python!" But in this case, I think a custom solution would create unnecessary maintenance and support issues.
